source 'http://rubygems.org'

gem 'sinatra', require: 'sinatra/base'
gem 'sinatra-contrib', require: 'sinatra/reloader'
gem 'activerecord', require: 'active_record'
gem 'sinatra-activerecord'
gem 'rake'
gem 'require_all'
gem 'pg'
gem 'thin'
gem 'bcrypt'
gem 'tux'
gem 'i18n'
gem 'awesome_print'
gem 'email_validator'
